name = "your-plugin-name"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
[version_metadata]
binding = "CLOUDFLARE_VERSION_METADATA"

[env.prod]

[observability]
enabled = true

